### ISSUE TITLE
Make available on CRAN

### ISSUE THREAD

**Issue by jhollway** [globalgov/manydata#97]

**Comment by henriquesposito** [comment]
I will try and start to get manydata ready for CRAN submission, I think we are close there.

**Comment by jhollway** [comment]
@henriquesposito , can you add a todo list here so that we can track any remaining items?

**Comment by henriquesposito** [comment]
# TODO list:

- [ ] Check package
  - [ ] Check package dependencies
  - [ ] Make sure all examples are in order or set with "donttest" instead of "dontrun"
  - [ ] Check spelling, best practices, and test coverage
  - [ ] Address any other issues with CMD check warnings and notes left
  - [ ] Open/Close a PR and check that documentation, NEWS, and description are updated
- [ ] Check CRAN requirements
  - [ ] `rhub::check_for_cran()` and/or `devtools::check_rhub()` to check for CRAN specific requirements and address any notes returned
  - [ ] check win-builder `devtools::check_win_devel()`
- [ ] Merge the PR and submit to CRAN (and fingers crossed)

Additional comments/TODO task :

- [ ] Should we move `{tibble}` to the improts section in description file to avoid CMD warnings?
- [ ] Are there any other resolve methods we would like to add for consolidate? The only one I can think we could add before submission is to resolve "in favor" of  a dataset over others.
- [ ] Should we test and/or have examples for the ´get_packages()´ function, or not, since there are concerns with GitHub download limits that often cause the CMD checks to fail?

@jhollway What do you think?

**Comment by jhollway** [comment]
Thanks @henriquesposito. Looks good.

On the additional comments:

- yes, avoid CMD warnings
- yes, 'in favour' (or equivalent)
- no, don't test `get_packages()`
